version: "3.9"
services:
  magento-plain-mysql:
    container_name: magento-plain-mysql
    hostname: magento-plain-mysql
    image: mysql:8.0.32-debian
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
  magento-plain-elasticsearch:
    container_name: magento-plain-elasticsearch
    hostname: magento-plain-elasticsearch
    image: elasticsearch:7.17.9
    ports:
      - "9202:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
volumes:
  mysql-data:
  elastic-data:
